<div id="kronolithViewAgenda" class="kronolithView" style="display:none">
<table class="kronolithView">
  <caption>
    <span id="kronolithLoadingagenda" class="kronolithLoading"></span>
    <span id="kronolithAgendaDate"></span>
    <span class="kronolithNavigation">
      <a class="kronolithGotoToday"><?php echo _("_Today") ?></a>
      <a title="<?php echo _("Previous") ?>" class="kronolithPrev">&lt;</a>
      <a title="<?php echo _("Next") ?>" class="kronolithNext">&gt;</a>
    </span>
  </caption>
  <tbody id="kronolithViewAgendaBody" class="kronolithViewBody">
    <tr id="kronolithAgendaTemplate" style="display:none">
      <td class="kronolithFirstCol"></td>
      <td>
      </td>
    </tr>
  </tbody>
</table>
</div>
