<div id="kronolithViewMonth" class="kronolithView kronolithViewMonth" style="display:none">

<div class="kronolithViewHead">
  <div class="kronolithRow">
    <div class="kronolithFirstCol">&nbsp;</div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_2) ?></span></div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_3) ?></span></div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_4) ?></span></div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_5) ?></span></div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_6) ?></span></div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_7) ?></span></div>
    <div class="kronolithCol"><span><?php echo NLS::getLangInfo(DAY_1) ?></span></div>
  </div>
</div>

<div class="kronolithViewBody">
  <div class="kronolithRow">
    <div class="kronolithFirstCol">44</div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">25</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">26</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">27</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">28</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">29</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">30</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">1</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
  </div>
  <div class="kronolithRow">
    <div class="kronolithFirstCol">45</div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">2</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
      <div class="kronolithEvent c1 kronolithEventFull">Restauração da Independência</div>
      <div class="kronolithEvent c2">10h Dia Mundial da Usabilidade</div>
      <div class="kronolithEvent c3">10h Dia Mundial da Usabilidade</div>
      <div class="kronolithEvent c4">10h Dia Mundial da Usabilidade</div>
      <div class="kronolithEvent c2">10h Dia Mundial da Usabilidade</div>
      <div class="kronolithMore"><a href="javascript:show('day');">...</a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">3</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">4</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">5</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">6</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">7</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">8</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
  </div>
  <div class="kronolithRow">
    <div class="kronolithFirstCol">46</div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">9</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">10</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">11</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">12</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">13</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">14</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">15</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
  </div>
  <div class="kronolithRow">
    <div class="kronolithFirstCol">47</div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">16</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">17</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">18</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">19</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">20</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">21</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">22</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
  </div>
  <div class="kronolithRow">
    <div class="kronolithFirstCol">48</div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">23</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">24</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">25</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">26</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">27</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">28</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">29</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
  </div>
  <div class="kronolithRow">
    <div class="kronolithFirstCol">49</div>
    <div class="kronolithCol kronolithToday">
      <div class="kronolithCorner"><div class="kronolithDay">30</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
      <div class="kronolithEvent c1">10h00 &#149; Dia Mundial da Usabilidade</div>
    </div>
    <div class="kronolithCol">
      <div class="kronolithCorner"><div class="kronolithDay">31</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">1</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">2</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">3</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">4</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
    <div class="kronolithCol kronolithOtherMonth">
      <div class="kronolithCorner"><div class="kronolithDay">5</div><a href="javascript:edit();" class="kronolithAdd"><?php echo $img_blank ?></a></div>
    </div>
  </div>
</div>

</div>
