<div id="kronolithViewTasks" class="kronolithView kronolithViewTasks" style="display:none">
<table class="kronolithView kronolithViewTasks">
  <caption>
    <div id="kronolithLoadingtasks" class="kronolithLoading"></div>
    <span><?php echo _("Tasks") ?></span>
  </caption>
  <tbody id="kronolithViewTasksBody" class="kronolithViewBody">
    <tr id="kronolithTasksTemplate" class="kronolithTaskRow" style="display:none">
      <td class="kronolithTaskCol">
      <div class="kronolithTaskCheckbox"/>
      </td>
    </tr>
  </tbody>
</table>
</div>
