<?php
/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in prefs.local.php or prefs.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use prefs-servername.php.
 */

// last browse file/directory
$_prefs['last_file'] = array(
    'value' => 0
);

// last sourceroot used
$_prefs['last_sourceroot'] = array(
    'value' => 0
);
