---
id: Browser
name: Browser
full: Browser detection library
description: >
  The Horde_Browser class provides an API for getting information about the
  current user's browser and its capabilities.
list: dev
type: library
