---
id: Alarm
name: Alarm
full: Alarm library
description: |
  An interface to deal with reminders, alarms and notifications through a standardized API. The following notification methods are currently available: standard Horde notifications, popups, emails.
list: dev
type: library
