<!-- Begin Deliverable Detail Dialog -->
<div id="hermesDeliverableDetail" class="hermesDialog" style="display:none;">
 <h1><?php echo _("Deliverable") ?></h1>
 <div class="hermesBudgetBox">
 <div class="hermesBudget">
   <h3><?php echo _("Budget") ?></h3>
   <div id="hermesStatText">
     <table><tbody>
       <tr><th><?php echo _("Logged")?></th><th><?php echo _("Budget") ?></th><th><?php echo _("Remaining") ?></th></tr>
       <tr><td></td><td></td><td></td></tr>
    </tbody></table>
   </div>
   <div id="hermesDeliverableStats"></div>
 </div>
 </div>
 <div id="hermesDeliverableBillable">&nbsp;</div>
 <div id="hermesDeliverableType">&nbsp;</div>
 <div id="hermesDeliverablesSlicelist">&nbsp;</div>
 <div class="clear"></div>
 <div class="hermesFormActions">
   <input id="hermesDeliverablesClose" type="button" class="horde-default" value="<?php echo _("Close") ?>" />
 </div>
</div>
<!-- End Deliverable Detail Dialog -->