<!-- Begin Deliverable Detail Dialog -->
<div id="hermesDeliverableDetail" class="hermesDialog" style="display:none;">
 <h2><?php echo _("Deliverable") ?></h2>
 <div id="hermesDeliverableStats">&nbsp;</div>
 <div id="hermesDeliverableType">&nbsp;</div>
 <div id="hermesDeliverableBillable">&nbsp;</div>
    <div class="hermesFormActions">
      <input id="hermesDeliverablesClose" type="button" class="horde-default" value="<?php echo _("Cancel") ?>" />
    </div>
</div>
<!-- End Deliverable Detail Dialog -->