<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "DTD/xhtml1-transitional.dtd">
<html>
<head>
<title><?php echo $module ?>: System Capabilities Test</title>
<style type="text/css">
body { font-family: Geneva,Arial,Helvetica,sans-serif; font-size: 90% }
td { font-family: Geneva,Arial,Helvetica,sans-serif }h1 { font-size: 110%; color: black; font-family: Verdana,Geneva,Arial,Helvetica,sans-serif; }
</style>
</head>

<body bgcolor="white" text="black">
