<?php
/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE! DO NOT COPY prefs.php TO prefs.local.php!
 * Local overrides ONLY MUST be placed in prefs.local.php or prefs.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use prefs-servername.php.
 */

$prefGroups['display'] = array(
    'column' => _("Display listings"),
    'label' => _("Display details"),
    'desc' => _("Set default display parameters."),
    'members' => array('addresses_perpage'));

// listing
$_prefs['addresses_perpage'] = array(
     'value' => 20,
     'locked' => false,
     'type' => 'number',
     'desc' => _("How many domain to display per page."));
