<div id="hermesTimerDialog" style="display:none;">
<form id="hermesTimerForm" action="">
<div>
  <label for="hermesTimerTitle">
    <input type="text" name="title" id="hermesTimerTitle" class="hermesLongField" />
    <div class="hermesDialogInfo"><?php echo _("Enter title for the new timer.") ?></div>
  </label>
</div>
<div class="hermesFormActions">
  <input id="hermesTimerSave" type="button" value="<?php echo _("Save") ?>" class="button ok" />
  <span class="hermesSeparator"><?php echo _("or") ?></span> <a class="hermesTimerCancel"><?php echo _("Cancel") ?></a>
</div>
</form>
</div>