<?php
/**
 * MIME Viewer configuration for Gollem.
 *
 * Settings in this file override settings in horde/config/mime_drivers.php.
 * All drivers configured in that file, but not configured here, will also
 * be used to display MIME content.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in mime_drivers.local.php.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use mime_drivers-servername.php.
 */

$mime_drivers = array(
    /* Image viewing. Gollem can display images inline. */
    'images' => array(
        'inline' => true,
        'handles' => array(
            'image/*'
        )
    )
);
