<?php
/**
 * @author     Jan Schneider <jan@horde.org>
 * @license    http://www.fsf.org/copyleft/lgpl.html LGPL
 * @category   Horde
 * @package    Core
 * @subpackage UnitTests
 */

class Horde_Core_UrlTest extends PHPUnit_Framework_TestCase
{
    public function testUrl()
    {
        $expected = array(
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'test.php',
            'test.php?PHPSESSID=',
            'http://example.com/hordeurl/test.php',
            'http://example.com/hordeurl/test.php?PHPSESSID=',
            'http://example.com/hordeurl/test.php',
            'http://example.com/hordeurl/test.php?PHPSESSID=',
            'http://example.com:443/hordeurl/test.php',
            'http://example.com:443/hordeurl/test.php?PHPSESSID=',
            'http://example.com:443/hordeurl/test.php',
            'http://example.com:443/hordeurl/test.php?PHPSESSID=',
            'https://example.com:80/hordeurl/test.php',
            'https://example.com:80/hordeurl/test.php?PHPSESSID=',
            'https://example.com:80/hordeurl/test.php',
            'https://example.com:80/hordeurl/test.php?PHPSESSID=',
            'https://example.com/hordeurl/test.php',
            'https://example.com/hordeurl/test.php?PHPSESSID=',
            'https://example.com/hordeurl/test.php',
            'https://example.com/hordeurl/test.php?PHPSESSID=',
            'http://example.com/hordeurl/test.php',
            'http://example.com/hordeurl/test.php?PHPSESSID=',
            'http://example.com/hordeurl/test.php',
            'http://example.com/hordeurl/test.php?PHPSESSID=',
            'http://example.com/hordeurl/test.php',
            'http://example.com/hordeurl/test.php?PHPSESSID=',
            'http://example.com/hordeurl/test.php',
            'http://example.com/hordeurl/test.php?PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'test.php?foo=1',
            'test.php?foo=1&amp;PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1',
            'http://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1',
            'http://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1',
            'http://example.com:443/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1',
            'http://example.com:443/hordeurl/test.php?foo=1&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1',
            'https://example.com:80/hordeurl/test.php?foo=1&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1',
            'https://example.com:80/hordeurl/test.php?foo=1&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1',
            'https://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1',
            'https://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1',
            'http://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1',
            'http://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1',
            'http://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1',
            'http://example.com/hordeurl/test.php?foo=1&PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1&bar=2',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1&bar=2',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1&bar=2',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1&bar=2',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'test.php?foo=1&amp;bar=2&amp;baz=3',
            'test.php?foo=1&amp;bar=2&amp;baz=3&amp;PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com:443/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&baz=3',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&baz=3',
            'https://example.com:80/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'https://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3',
            'http://example.com/hordeurl/test.php?foo=1&bar=2&baz=3&PHPSESSID=',
        );

        $uris = array(
            'test.php',
            'test.php?foo=1',
            'test.php?foo=1&bar=2',
            'test.php?foo=1&amp;bar=2',
            'test.php?foo=1&amp;bar=2&amp;baz=3'
        );
        $fulls = array(false, true);
        $ssls = array(0, 1, 3);
        $ports = array(80, 443);
        $expect = 0;
        $GLOBALS['registry'] = new Registry();
        $GLOBALS['conf']['server']['name'] = 'example.com';

        foreach ($uris as $uri) {
            foreach ($fulls as $full) {
                foreach ($ssls as $ssl) {
                    $GLOBALS['conf']['use_ssl'] = $ssl;
                    foreach ($ports as $port) {
                        $GLOBALS['conf']['server']['port'] = $port;
                        $this->assertEquals($expected[$expect++], (string)Horde::url($uri, $full, array('append_session' => -1)), sprintf('URI: %s, full: %s, SSL: %s, port: %d, session: -1', $uri, var_export($full, true), $ssl, $port));
                        unset($_COOKIE[session_name()]);
                        $this->assertEquals($expected[$expect++], (string)Horde::url($uri, $full, array('append_session' => 0)), sprintf('URI: %s, full: %s, SSL: %s, port: %d, session: 0, cookie: false', $uri, var_export($full, true), $ssl, $port));
                        $_COOKIE[session_name()] = array();
                        $this->assertEquals($expected[$expect++], (string)Horde::url($uri, $full, array('append_session' => 0)), sprintf('URI: %s, full: %s, SSL: %s, port: %d, session: 0, cookie: true', $uri, var_export($full, true), $ssl, $port));
                        $this->assertEquals($expected[$expect++], (string)Horde::url($uri, $full, array('append_session' => 1)), sprintf('URI: %s, full: %s, SSL: %s, port: %d, session: 1, cookie: true', $uri, var_export($full, true), $ssl, $port));
                    }
                }
            }
        }
    }
}

class Registry {

    function get()
    {
        return '/hordeurl';
    }

}
