<?php
/**
 * See horde/config/prefs.php for documentation on the structure of this file.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in pref.local.php or pref.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use prefs-servername.php.
 */

$_prefs = array();

$_prefs['sync_data'] = array(
    'value' => 'a:0:{}',
    'locked' => false,
    'type' => 'implicit'
);
