<div class="pagebody">
<table class="pagelist striped sortable" style="width:100%" cellspacing="0">
<thead>
 <tr>
  <th style="width:40%"><?php echo _("Page") ?></th>
  <th style="width:10%"><?php echo _("Version") ?></th>
  <th style="width:25%"><?php echo _("Author") ?></th>
  <th style="width:25%"><?php echo _("Creation Date") ?></th>
  <?php if (!empty($hits)): ?>
  <th class="nowrap" style="width:5%"><?php echo _("Page Views") ?></th>
  <?php endif; ?>
 </tr>
</thead>
<tbody>
