<?php
/**
 * This file contains any "Message Of The Day" Type information It will be
 * included below the log-in form on the login page.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in motd.local.php or motd.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use motd-servername.php.
 */

ob_start();

?>
<br />
<table width="100%"><tr><td align="center"><img src="<?php echo Horde_Themes::img('horde-power1.png') ?>" alt="Powered by Horde" /></td></tr></table>

<?php
$motd = ob_get_clean();
