<?php
/**
 * This file defines a custom list of words that will be added to the spell
 * checker dictionary.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in spelling.local.php or spelling.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use spelling-servername.php.
 */

/* Default list (English). */
$ignore_list = array(
    'jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct',
    'nov', 'dec', 'fwd', 'http', 'https', 'html', 'email', 'bcc', 'jpg', 'gif'
);
